version: '3.8'

services:
  frontend:
    build: ./appgridv2
    ports:
      - "4200:80"  # Puerto 80 de NGINX mapeado al 4200 local
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
